version: '3.9'
services:
  app:
    container_name: wpp-it-app
    restart: always
    build: .
    ports:
      - '8080:8080'
    links:
      - redis
  redis:
    container_name: wpp-it-redis
    image: redis:latest